using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.LowLevel;
using UnityEngine.SceneManagement;

public enum UIState
{
    Default,
    Start,
    Pause,
    ControlMethodSelection,
    Credits,
}

public class GUIManager : MonoBehaviour
{
    [SerializeField] private GameObject _pauseScreen;
    [SerializeField] private GameObject _startScreen;
    [SerializeField] private GameObject _controls;
    [SerializeField] private GameObject _desktopControls;
    [SerializeField] private GameObject _mobileControls;
    [SerializeField] private GameObject _creditsScreen;
    [SerializeField] private KeyboardAndMouseController _keyBoardAndMouseController;
    [SerializeField] private GameObject _defaultButtonReturn;
    [SerializeField] private GameObject _defaultButtonStart;
    [SerializeField] private GameObject _defaultButtonControls;
    [SerializeField] private GameObject _defaultButtonCredits;
    [SerializeField] private string _mainMenuSceneName;
    [SerializeField] private InputActionReference defaultNavigateInputActionReference;
    [SerializeField] private GameObject _mobilePauseButton;
    [SerializeField] private GameObject _mobileSkipButton;
    [SerializeField] private GameObject _mobileOnScreenSticks;
    [SerializeField] private GameObject _subtitles;
    [SerializeField] private TMP_Text _infoText;
    private PlayerActionsAutoGenerated _playerActions;
    private bool _useTouchControls;
    private bool _isMobileSkipEnabled=false;
    private bool _audioSkip;
    private bool _subtitlesSkip;
    private UIState _currentState;
    private UIState _storedUIState = UIState.Default;
    private AudioTrigger _activeAudioTrigger;

    public void Awake()
    {
        _playerActions = new PlayerActionsAutoGenerated();
    }


    public void Start()
    {
        _mobileSkipButton.SetActive(false);
        DeactivateScreens();
        DeactivateTouchControls(true);
        _currentState = UIState.Start;
        SwitchState(_currentState);
        _useTouchControls = PlatformManager.IsTouchScreen();
        if (_useTouchControls)
        {
            _mobileControls.SetActive(true);
            _desktopControls.SetActive(false);
        }
        else
        {
            _mobileControls.SetActive(false);
            _desktopControls.SetActive(true);
        }

            var platform = PlatformManager.Current;

        // Debug / info label
        if (_infoText != null)
        {
            _infoText.enabled = true;
            _infoText.text = "Platform: " + platform.ToString();
        }
    }



    void OnEnable()
    {
        _playerActions.Player.Enable();
        _playerActions.Player.Menu.performed += DisplayPauseScreen;

        Events.AudioStart.Subscribe(OnAudioStarted);
        Events.AudioStop.Subscribe(OnAudioStopped);

        Events.SubtitlesSkip.Subscribe(SubtitlesSkip);
        Events.SubtitlesStop.Subscribe(OnSubtitlesStopped);  

        SetupNavigationForWebGL();
    }

    void OnDisable()
    {
        _playerActions.Player.Disable();
        _playerActions.Player.Menu.performed -= DisplayPauseScreen;

        Events.AudioStart.Unsubscribe(OnAudioStarted);
        Events.AudioStop.Unsubscribe(OnAudioStopped);

        Events.SubtitlesSkip.Unsubscribe(SubtitlesSkip);
        Events.SubtitlesStop.Unsubscribe(OnSubtitlesStopped); // FIXED
    }

    private void OnAudioStarted(AudioTrigger trigger)
    {
        _activeAudioTrigger = trigger;
        EnableSkipButton();
    }

    private void OnAudioStopped(AudioTrigger trigger)
    {
        if (_activeAudioTrigger == trigger)
            _activeAudioTrigger = null;

        AudioSkip(); // keep your existing GUI skip-flag flow
    }

    private void OnSubtitlesStopped()
    {
        _subtitlesSkip = true;
        DisableSkipButton();
    }

    private void AudioSkip()
    {
        _audioSkip=true;
        DisableSkipButton();
    }

    private void SubtitlesSkip()
    {
        _subtitlesSkip=true;
        DisableSkipButton();
    }

    private void EnableMouse()
    {
        if (!PlatformManager.IsTouchScreen())
        {
            Cursor.lockState = CursorLockMode.None;
        }
    }

    private void DisableMouse()
    {
        if (!PlatformManager.IsTouchScreen())
        {
            Cursor.lockState = CursorLockMode.Locked;
        }
    }

    void SwitchState(UIState newState)
    {
        switch (newState)
        {

            case UIState.Pause:
                EnableMouse();
                Pause();
                _pauseScreen.SetActive(true);
                EventSystem.current.SetSelectedGameObject(_defaultButtonReturn);
                break;
            case UIState.ControlMethodSelection:
                _storedUIState = _currentState;
                EnableMouse();
                Pause();
                _controls.SetActive(true);
                EventSystem.current.SetSelectedGameObject(_defaultButtonControls);
                break;
            case UIState.Credits:
                _storedUIState = _currentState;
                EnableMouse();
                Pause();
                _creditsScreen.SetActive(true);
                EventSystem.current.SetSelectedGameObject(_defaultButtonCredits);
                break;
            case UIState.Start:
                EnableMouse();
                Pause();
                _startScreen.SetActive(true);
                EventSystem.current.SetSelectedGameObject(_defaultButtonStart);
                break;


            default:
                Unpause();
                break;
        }
        _currentState = newState;
    }

    void Pause()
    {
        _subtitles.SetActive(false);
        _keyBoardAndMouseController.enabled = false;
        Time.timeScale = 0;
        AudioListener.pause = true;
        DeactivateTouchControls();
    }

    void Unpause()
    {
        _subtitles.SetActive(true);
        Time.timeScale = 1;
        _keyBoardAndMouseController.enabled = true;
        AudioListener.pause = false;
        ActivateTouchControls();
    }

    private void DeactivateTouchControls(bool forceDeactivation=false)
    {
        if (_useTouchControls||forceDeactivation)
        { 
            _mobilePauseButton.SetActive(false);
            if (_mobileSkipButton.activeSelf == true)
            {
                _isMobileSkipEnabled = true;
                _mobileSkipButton.SetActive(false);
            }
            else
            {
                _isMobileSkipEnabled = false;
            }
            _mobileOnScreenSticks.SetActive(false);
        }
    }

    private void ActivateTouchControls()
    {
        if (_useTouchControls)
        {
            _mobilePauseButton.SetActive(true);
            if (_isMobileSkipEnabled)
            {
                _mobileSkipButton.SetActive(true);
            }
            _mobileOnScreenSticks.SetActive(true);
        }
    }

    private void EnableSkipButton()
    {
        if (_useTouchControls)
        {
             _audioSkip=false;
             _subtitlesSkip=false;
             _isMobileSkipEnabled = true;
            _mobileSkipButton.SetActive(true);
        }
    }

    private void DisableSkipButton()
    {
        if (_useTouchControls && _subtitlesSkip && _audioSkip)
        {
            _audioSkip = false;
            _subtitlesSkip = false;
            _isMobileSkipEnabled = false;
            _mobileSkipButton.SetActive(false);
        }
    }

    public void TriggerSkipEvents()
    {
        if (_useTouchControls)
        {
            if (_activeAudioTrigger != null)
                _activeAudioTrigger.StopAudioExternally();

            Events.SubtitlesSkip.Publish();
        }
    }

    public void DisplayPauseScreen(InputAction.CallbackContext context)
    {
        if (CheckForOpenScreens() == false)
        {
            DeactivateScreens();
            SwitchState(UIState.Pause);
        }
    }

    public void DisplayPauseScreen()
    {
        if (CheckForOpenScreens() == false)
        {
            DeactivateScreens();
            SwitchState(UIState.Pause);
        }
    }

    public void DisplayControlMethodScreen()
    {
        DeactivateScreens();
        SwitchState(UIState.ControlMethodSelection);
    }

    public void DisplayCreditsScreen()
    {
        DeactivateScreens();
        SwitchState(UIState.Credits);
    }

    private bool CheckForOpenScreens()
    {
        if (_startScreen.activeSelf == true||_pauseScreen.activeSelf == true || _controls.activeSelf == true|| _creditsScreen.activeSelf == true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public void DeactivateScreens()
    {
        DisableMouse();
        Unpause();
        _startScreen.SetActive(false);
        _pauseScreen.SetActive(false);
        _controls.SetActive(false);
        _creditsScreen.SetActive(false);

        if (_storedUIState != UIState.Default)
        {
            SwitchState(_storedUIState);
            _storedUIState = UIState.Default;
        }

    }

    public void LoadMainMenu()
    {
        SceneManager.LoadScene(_mainMenuSceneName);
    }

    private void SetupNavigationForWebGL()
    {
        // This is required to rectify a bug in WebGL deployments where up and down does not work on GUI screens
        // Note: Not currently working in this build.  Believe because we are still using old input.  Further research required.
        InputBinding binding = new InputBinding()
        {
            path = "<Gamepad>/leftStick",
            processors = "webglnavigation"
        };

        defaultNavigateInputActionReference.action.AddBinding(binding);
    }

}
