using UnityEngine;
using UnityEngine.InputSystem;

public class KeyboardAndMouseController : MonoBehaviour
{
    [SerializeField] private float keyboardForwardSpeed = 2;
    [SerializeField] private float keyboardHorizontalSpeed = 2;

    [SerializeField] private Camera mainCamera;
    [SerializeField] private float lookSensitivity = 1f;

    [SerializeField] private float mouseSmooth = 18f;

    private float _targetXRotation;
    private float _targetYRotation;

    private PlayerActionsAutoGenerated _playerActions;
    private Transform myTransform;
    private Transform cameraTransform;

    private float _xRotation;
    private float _yRotation;
    private Vector3 _moveDirection;

    private bool pauseMovement;
    private AudioTrigger _activeAudioTrigger;

    private void Awake()
    {
        _playerActions = new PlayerActionsAutoGenerated();
        _playerActions.Player.Interact.performed += OnInteract;

        myTransform = transform;
        cameraTransform = mainCamera.transform;
    }

    private void OnEnable()
    {
        _playerActions.Player.Enable();
        Events.AudioStart.Subscribe(PauseMovementForAudio);
        Events.AudioStop.Subscribe(UnPauseMovement);
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();

        Events.AudioStart.Unsubscribe(PauseMovementForAudio);
        Events.AudioStop.Unsubscribe(UnPauseMovement);
    }

    private void OnDestroy()
    {
        _playerActions.Player.Interact.performed -= OnInteract;
    }

    private void Update()
    {
        HandleMovement();
        HandleLook();
    }

    private void OnInteract(InputAction.CallbackContext context)
    {
        if (_activeAudioTrigger != null)
            _activeAudioTrigger.StopAudioExternally();
        Events.SubtitlesSkip.Publish();
    }

    private void HandleLook()
    {
        Vector2 lookVector = _playerActions.Player.Look.ReadValue<Vector2>();

        _targetYRotation += lookVector.x * lookSensitivity;
        _targetXRotation -= lookVector.y * lookSensitivity;

        _targetXRotation = Mathf.Clamp(_targetXRotation, -70f, 70f);

        _xRotation = Mathf.Lerp(_xRotation, _targetXRotation, mouseSmooth * Time.deltaTime);
        _yRotation = Mathf.Lerp(_yRotation, _targetYRotation, mouseSmooth * Time.deltaTime);

        cameraTransform.localRotation = Quaternion.Euler(_xRotation, 0f, 0f);
        myTransform.rotation = Quaternion.Euler(0f, _yRotation + 180f, 0f);
    }


    private void PauseMovementForAudio(AudioTrigger trigger)
    {
        pauseMovement = true;
        _activeAudioTrigger = trigger;
    }

    private void UnPauseMovement(AudioTrigger sender)
    {
        pauseMovement = false;
    }

    private void HandleMovement()
    {
        if (pauseMovement) return;

        Vector2 moveVector = _playerActions.Player.Move.ReadValue<Vector2>();
        _moveDirection = new Vector3(moveVector.x, 0, moveVector.y);

        myTransform.Translate(Vector3.forward * (_moveDirection.z * Time.deltaTime * keyboardForwardSpeed));
        myTransform.Translate(Vector3.right * (_moveDirection.x * Time.deltaTime * keyboardHorizontalSpeed));
    }
}
