using System.Collections;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.Audio;
using UnityEngine.InputSystem;

public class KeyboardAndMouseController : MonoBehaviour
{
    [SerializeField] private float keyboardForwardSpeed = 2;
    [SerializeField] private float keyboardHorizontalSpeed = 2;

    [SerializeField] private Camera mainCamera;
    [SerializeField] private float lookSensitivity = 1f;

    [SerializeField] private float mouseSmooth = 18f;

    private float _targetXRotation;
    private float _targetYRotation;

    private PlayerActionsAutoGenerated _playerActions;
    private Transform myTransform;
    private Transform cameraTransform;

    private float _xRotation;
    private float _yRotation;
    private Vector3 _moveDirection;

    private bool _pauseMovement;
    private bool _pauseLook;
    private InfoPointController _activeInfoPointController;
    private Transform _infoPointPlayerOrientation;

    private void Awake()
    {
        _playerActions = new PlayerActionsAutoGenerated();
        _playerActions.Player.Interact.performed += OnInteract;

        myTransform = transform;
        cameraTransform = mainCamera.transform;
    }

    private void OnEnable()
    {
        _playerActions.Player.Enable();
        Events.InfoPointStart.Subscribe(PauseMovementForAudio);
        Events.InfoPointStop.Subscribe(UnPauseMovement);
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();

        Events.InfoPointStart.Unsubscribe(PauseMovementForAudio);
        Events.InfoPointStop.Unsubscribe(UnPauseMovement);
    }

    private void OnDestroy()
    {
        _playerActions.Player.Interact.performed -= OnInteract;
    }

    private void Update()
    {
        HandleMovement();
        HandleLook();
    }

    private void OnInteract(InputAction.CallbackContext context)
    {
        if (_activeInfoPointController != null)
            _activeInfoPointController.StopAudioExternally();
        Events.SubtitlesSkip.Publish();
    }

    private void HandleLook()
    {
        if (_pauseLook) return;
        Vector2 lookVector = _playerActions.Player.Look.ReadValue<Vector2>();

        _targetYRotation += lookVector.x * lookSensitivity;
        _targetXRotation -= lookVector.y * lookSensitivity;

        _targetXRotation = Mathf.Clamp(_targetXRotation, -70f, 70f);

        _xRotation = Mathf.Lerp(_xRotation, _targetXRotation, mouseSmooth * Time.deltaTime);
        _yRotation = Mathf.Lerp(_yRotation, _targetYRotation, mouseSmooth * Time.deltaTime);

        cameraTransform.localRotation = Quaternion.Euler(_xRotation, 0f, 0f);
        myTransform.rotation = Quaternion.Euler(0f, _yRotation + 180f, 0f);
    }


    private void PauseMovementForAudio(InfoPointController infoPointController)
    {
        _pauseMovement = true;
        _pauseLook = true;
        _activeInfoPointController = infoPointController;
        _infoPointPlayerOrientation = _activeInfoPointController.GetInfoPointPlayerOrientation();
        StartCoroutine(UpdatePlayerOrientation());
    }

    IEnumerator UpdatePlayerOrientation()
    {
        if (_infoPointPlayerOrientation == null)
            yield break;

        float rotationThreshold = 0.5f;
        float rotationSpeed = 180f; // degrees per second

        while (true)
        {
            if (_infoPointPlayerOrientation == null)
                yield break;

            Vector3 directionToTarget = _infoPointPlayerOrientation.forward;
            directionToTarget.y = 0f;

            if (directionToTarget.sqrMagnitude < 0.001f)
                yield return null;

            Quaternion targetRotation = Quaternion.LookRotation(directionToTarget);

            transform.rotation = Quaternion.RotateTowards(
                transform.rotation,
                targetRotation,
                rotationSpeed * Time.deltaTime
            );

            float angleDifference = Quaternion.Angle(transform.rotation, targetRotation);

            if (angleDifference <= rotationThreshold)
                break;

            yield return null;
        }

        Vector3 finalDirection = _infoPointPlayerOrientation.forward;
        finalDirection.y = 0f;

        if (finalDirection.sqrMagnitude > 0.001f)
        {
            Quaternion finalRotation = Quaternion.LookRotation(finalDirection);
            transform.rotation = finalRotation;
        }

        float syncedY = transform.eulerAngles.y - 180f;
        _targetYRotation = syncedY;
        _yRotation = syncedY;

        if (_activeInfoPointController != null && _activeInfoPointController.IsAudioPlaying())
        {
            _pauseLook = false;
        }
    }


    private void UnPauseMovement(InfoPointController infoPointController)
    {
        _pauseMovement = false;
        _pauseLook = false;
    }

    private void HandleMovement()
    {
        if (_pauseMovement) return;

        Vector2 moveVector = _playerActions.Player.Move.ReadValue<Vector2>();
        _moveDirection = new Vector3(moveVector.x, 0, moveVector.y);

        myTransform.Translate(Vector3.forward * (_moveDirection.z * Time.deltaTime * keyboardForwardSpeed));
        myTransform.Translate(Vector3.right * (_moveDirection.x * Time.deltaTime * keyboardHorizontalSpeed));
    }
}
