using System.Collections;
using UnityEngine;
using UnityEngine.InputSystem;

public class KeyboardAndMouseController : MonoBehaviour
{
    [SerializeField] private float keyboardForwardSpeed = 2;
    [SerializeField] private float keyboardHorizontalSpeed = 2;

    [SerializeField] private Camera mainCamera;
    [SerializeField] private float lookSensitivity = 1f;

    [SerializeField] private float mouseSmooth = 18f;

    private float _targetXRotation;
    private float _targetYRotation;

    private PlayerActionsAutoGenerated _playerActions;
    private Transform myTransform;
    private Transform cameraTransform;

    private float _xRotation;
    private float _yRotation;
    private Vector3 _moveDirection;

    private bool _pauseMovement;
    private bool _pauseLook;
    private InfoPointController _activeInfoPointController;
    private Transform _infoPointPlayerOrientation;

    private Vector3 _directionToFace;
    private bool _isAutoAligning;
    private bool _isInfoPointAudioActive;
    private Coroutine _updateOrientationCoroutine;

    private void Awake()
    {
        _playerActions = new PlayerActionsAutoGenerated();
        _playerActions.Player.Interact.performed += OnInteract;

        myTransform = transform;
        cameraTransform = mainCamera.transform;
    }

    private void OnEnable()
    {
        _playerActions.Player.Enable();
        Events.InfoPointStart.Subscribe(PauseMovementForAudio);
        Events.InfoPointStop.Subscribe(UnPauseMovement);
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();

        Events.InfoPointStart.Unsubscribe(PauseMovementForAudio);
        Events.InfoPointStop.Unsubscribe(UnPauseMovement);
    }

    private void OnDestroy()
    {
        _playerActions.Player.Interact.performed -= OnInteract;
    }

    private void Update()
    {
        HandleMovement();
        HandleLook();
    }

    private void OnInteract(InputAction.CallbackContext context)
    {
        if (_activeInfoPointController != null)
            _activeInfoPointController.StopAudioExternally();
        Events.SubtitlesSkip.Publish();
    }

    private void HandleLook()
    {
        if (_pauseLook) return;
        Vector2 lookVector = _playerActions.Player.Look.ReadValue<Vector2>();

        _targetYRotation += lookVector.x * lookSensitivity;
        _targetXRotation -= lookVector.y * lookSensitivity;

        _targetXRotation = Mathf.Clamp(_targetXRotation, -70f, 70f);

        _xRotation = Mathf.Lerp(_xRotation, _targetXRotation, mouseSmooth * Time.deltaTime);
        _yRotation = Mathf.Lerp(_yRotation, _targetYRotation, mouseSmooth * Time.deltaTime);

        cameraTransform.localRotation = Quaternion.Euler(_xRotation, 0f, 0f);
        myTransform.rotation = Quaternion.Euler(0f, _yRotation + 180f, 0f);
    }


    private void PauseMovementForAudio(InfoPointController infoPointController)
    {
        _pauseMovement = true;
        _pauseLook = true;

        _isInfoPointAudioActive = true;
        _isAutoAligning = true;

        _activeInfoPointController = infoPointController;
        _infoPointPlayerOrientation = _activeInfoPointController.GetInfoPointPlayerOrientation();

        if (_updateOrientationCoroutine != null)
            StopCoroutine(_updateOrientationCoroutine);

        _updateOrientationCoroutine = StartCoroutine(UpdatePlayerOrientation());
    }

    IEnumerator UpdatePlayerOrientation()
    {

        if (_infoPointPlayerOrientation == null)
            yield break;

        // Thresholds and speeds used for the automatic alignment
        float rotationThreshold = 0.1f;   // How close in degrees we need to be before considering rotation complete
        float positionThreshold = 0.1f;   // How close in world units we need to be before considering movement complete
        float pitchThreshold = 0.1f;        // How close in world units we need to be before considering pitch movement complete
        float rotationSpeed = 180f;       // Degrees per second for auto-rotation
        float moveSpeed = 1.5f;           // Units per second for auto-movement

        // Determine whether this info point wants the player to move into position
        bool shouldMove = _activeInfoPointController != null &&
                          _activeInfoPointController.ShouldMovePlayerToInfoPoint();

        // Keep updating until the player has finished rotating and moving
        while (true)
        {
            if (_infoPointPlayerOrientation == null)
                yield break;

            // Default to current position in case movement is not required
            Vector3 targetPosition = transform.position;

            if (shouldMove)
            {
                // Use the info point's position as the target position,
                targetPosition = _infoPointPlayerOrientation.position;
                targetPosition.y = transform.position.y;

                // Move the player toward the target
                transform.position = Vector3.MoveTowards(
                    transform.position,
                    targetPosition,
                    moveSpeed * Time.deltaTime
                );
            }

            if (shouldMove)
            {
                // For normal info points face the direction defined by the orientation object's forward vector
                _directionToFace = _infoPointPlayerOrientation.forward;
                _directionToFace.y = 0f; 
            }
            else
            {
                // For character interactions face toward the target's position instead
                _directionToFace = _infoPointPlayerOrientation.position - myTransform.position;
                _directionToFace.y = 0f; 
            }

            // If the direction is too small wait until next frame and try again
            if (_directionToFace.sqrMagnitude < 0.001f)
            {
                yield return null;
                continue;
            }

            // Create the target rotation
            Quaternion targetRotation = Quaternion.LookRotation(_directionToFace);

            // Rotate toward the desired rotation
            transform.rotation = Quaternion.RotateTowards(
                transform.rotation,
                targetRotation,
                rotationSpeed * Time.deltaTime
            );

            _xRotation = Mathf.MoveTowards(_xRotation, 0f, rotationSpeed * Time.deltaTime);
            _targetXRotation = _xRotation;
            cameraTransform.localRotation = Quaternion.Euler(_xRotation, 0f, 0f);

            // Determine angle distance from target
            float angleDifference = Quaternion.Angle(transform.rotation, targetRotation);

            bool pitchComplete = Mathf.Abs(_xRotation) <= pitchThreshold;

            if (shouldMove)
            {
                float distance = Vector3.Distance(transform.position, targetPosition);

                if (angleDifference <= rotationThreshold && distance <= positionThreshold && pitchComplete)
                {
                    break;
                }
            }
            else
            {
                if (angleDifference <= rotationThreshold && pitchComplete)
                {
                    break;
                }
            }



            yield return null;
        }

        if (shouldMove)
        {
            // Snap exactly to the final target position at the end
            Vector3 finalPosition = _infoPointPlayerOrientation.position;
            finalPosition.y = transform.position.y;
            transform.position = finalPosition;
        }

        Vector3 finalDirection;

        if (shouldMove)
        {
            // For normal info points, final facing direction is the orientation object's forward
            finalDirection = _infoPointPlayerOrientation.forward;
        }
        else
        {
            // For character interactions, final facing direction is toward the target's position
            finalDirection = _infoPointPlayerOrientation.position - myTransform.position;
        }

        finalDirection.y = 0f; 

        if (finalDirection.sqrMagnitude > 0.001f)
        {
            // Snap exactly to the final target rotation
            transform.rotation = Quaternion.LookRotation(finalDirection);
        }

        // Sync the controller's stored yaw values with the new transform rotation
        float syncedY = transform.eulerAngles.y - 180f;
        _targetYRotation = syncedY;
        _yRotation = syncedY;

        _xRotation = 0f;
        _targetXRotation = 0f;
        cameraTransform.localRotation = Quaternion.Euler(0f, 0f, 0f);

        // Auto-alignment is now finished
        _isAutoAligning = false;
        _updateOrientationCoroutine = null;

        // Allow look once alignment is finished, but only while audio is still active
        if (_isInfoPointAudioActive)
        {
            _pauseLook = false;
        }

        // Movement only resumes when both alignment and audio are done
        TryRestoreControl();
    }

    private void TryRestoreControl()
    {
        // Only restore movement when both audio and auto-alignment are finished
        if (!_isInfoPointAudioActive && !_isAutoAligning)
        {
            _pauseMovement = false;
            _pauseLook = false;

            _activeInfoPointController = null;
            _infoPointPlayerOrientation = null;
        }
    }

    private void UnPauseMovement(InfoPointController infoPointController)
    {
        // Ignore stop events from older / different info points
        if (infoPointController != _activeInfoPointController)
            return;

        _isInfoPointAudioActive = false;
        TryRestoreControl();
    }

    private void HandleMovement()
    {
        if (_pauseMovement) return;

        Vector2 moveVector = _playerActions.Player.Move.ReadValue<Vector2>();
        _moveDirection = new Vector3(moveVector.x, 0, moveVector.y);

        myTransform.Translate(Vector3.forward * (_moveDirection.z * Time.deltaTime * keyboardForwardSpeed));
        myTransform.Translate(Vector3.right * (_moveDirection.x * Time.deltaTime * keyboardHorizontalSpeed));
    }
}
