using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;

public class PlayerNavigationController : MonoBehaviour
{
    private enum NavigationMode
    {
        None,
        FreeMove,
        InfoPoint
    }

    [Header("References")]
    [SerializeField] private NavMeshAgent agent;
    [SerializeField] private KeyboardAndMouseController keyboardController;

    [Header("Arrival Settings")]
    [SerializeField] private float freeMoveArrivalDistance = 0.2f;

    private NavigationMode _navigationMode = NavigationMode.None;
    private InfoPointController _currentTargetInfoPoint;
    private PlayerActionsAutoGenerated _playerActions;

    private void Awake()
    {
        if (agent == null)
            agent = GetComponent<NavMeshAgent>();

        _playerActions = new PlayerActionsAutoGenerated();
        //agent.updateRotation = false;
    }

    private void OnEnable()
    {
        _playerActions.Player.Enable();
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();
    }

    private void Update()
    {
        //CancelNavigationIfManualInputDetected();

        switch (_navigationMode)
        {
            case NavigationMode.FreeMove:
                CheckFreeMoveArrival();
                break;

            case NavigationMode.InfoPoint:
                break;
        }
    }

    public void MoveToPoint(Vector3 destination)
    {
        if (agent == null)
            return;

        _navigationMode = NavigationMode.FreeMove;
        _currentTargetInfoPoint = null;

        agent.isStopped = false;
        agent.updatePosition = true;
        //agent.Warp(transform.position);
        agent.nextPosition = transform.position;
        agent.SetDestination(destination);

        if (keyboardController != null)
        {
            keyboardController.BeginLevelView();
            keyboardController.SetManualMovementEnabled(false);
        }
    }

    public void MoveToInfoPoint(Vector3 destination, InfoPointController infoPoint)
    {
        if (agent == null || infoPoint == null)
            return;

        _navigationMode = NavigationMode.InfoPoint;
        _currentTargetInfoPoint = infoPoint;

        if (keyboardController != null)
        {
            keyboardController.BeginLevelView();
            keyboardController.SetManualMovementEnabled(false);
        }

        agent.isStopped = false;
        agent.updatePosition = true;
        //agent.Warp(transform.position);
        agent.nextPosition = transform.position;
        agent.SetDestination(destination);
    }

    public void StopAtInfoPoint(InfoPointController infoPoint)
    {
        if (_navigationMode != NavigationMode.InfoPoint)
            return;

        if (infoPoint != _currentTargetInfoPoint)
            return;

        StopNavigationInternal();
    }

    public void StopNavigation()
    {
        StopNavigationInternal();
    }

    public void RestoreAgentAfterInfoPoint()
    {
        if (agent == null)
            return;

        if (!agent.enabled)
            agent.enabled = true;

        bool warped = agent.Warp(transform.position);
        if (!warped)
        {
            Debug.LogWarning("Failed to warp NavMeshAgent back to player position.");
        }

        agent.isStopped = true;
        agent.ResetPath();
        agent.updatePosition = true;
    }

    private void CheckFreeMoveArrival()
    {
        if (agent == null || agent.pathPending)
            return;

        if (agent.remainingDistance <= Mathf.Max(agent.stoppingDistance, freeMoveArrivalDistance))
        {
            if (!agent.hasPath || agent.velocity.sqrMagnitude < 0.01f)
            {
                StopNavigationInternal();
            }
        }
    }

    //public void SyncAgentToTransform()
    //{
    //    if (agent == null)
    //        return;
    //
    //    agent.nextPosition = transform.position;
    //}

    private void CancelNavigation()
    {
        if (_navigationMode == NavigationMode.None)
            return;

        Vector2 moveInput = _playerActions.Player.Move.ReadValue<Vector2>();

        if (moveInput.sqrMagnitude > 0.01f)
        {
            StopNavigationInternal();
        }
    }

    private void StopNavigationInternal()
    {
        if (agent != null)
        {
            agent.isStopped = true;
            agent.ResetPath();
            agent.updatePosition = false;
        }

        _navigationMode = NavigationMode.None;
        _currentTargetInfoPoint = null;
        if (keyboardController != null)
        {
            keyboardController.EndLevelView();
            keyboardController.SetManualMovementEnabled(true);
        }
    }


    public bool IsNavigationActive()
    {
        return _navigationMode != NavigationMode.None;
    }

    public bool IsNavigatingToInfoPoint(InfoPointController infoPoint)
    {
        return _navigationMode == NavigationMode.InfoPoint &&
               _currentTargetInfoPoint == infoPoint;
    }
}