using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;

public class PlayerNavigationController : MonoBehaviour
{
    private enum NavigationMode
    {
        None,
        FreeMove,
        InfoPoint
    }

    [Header("References")]
    [SerializeField] private NavMeshAgent agent;
    [SerializeField] private KeyboardAndMouseController keyboardController;

    [Header("Arrival Settings")]
    [SerializeField] private float freeMoveArrivalDistance = 0.2f;

    private NavigationMode _navigationMode = NavigationMode.None;
    private InfoPointController _currentTargetInfoPoint;
    private PlayerActionsAutoGenerated _playerActions;

    private void Awake()
    {
        if (agent == null)
            agent = GetComponent<NavMeshAgent>();

        _playerActions = new PlayerActionsAutoGenerated();
    }

    private void OnEnable()
    {
        _playerActions.Player.Enable();
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();
    }

    private void Update()
    {
        CancelNavigationIfManualInputDetected();

        switch (_navigationMode)
        {
            case NavigationMode.FreeMove:
                CheckFreeMoveArrival();
                break;

            case NavigationMode.InfoPoint:
                // Info point stop is handled by the InfoPoint trigger.
                // Optional fallback could be added here later if needed.
                break;
        }
    }

    public void MoveToPoint(Vector3 destination)
    {
        if (agent == null)
            return;

        _navigationMode = NavigationMode.FreeMove;
        _currentTargetInfoPoint = null;

        agent.isStopped = false;
        agent.SetDestination(destination);

        SetManualMovementEnabled(false);

        Debug.Log("Navigating to free-move point: " + destination);
    }

    public void MoveToInfoPoint(Vector3 destination, InfoPointController infoPoint)
    {
        if (agent == null || infoPoint == null)
            return;

        _navigationMode = NavigationMode.InfoPoint;
        _currentTargetInfoPoint = infoPoint;

        agent.isStopped = false;
        Debug.Log("Destination: " + destination);
        agent.SetDestination(destination);

        SetManualMovementEnabled(false);

        Debug.Log("Navigating to info point: " + infoPoint.name);
    }

    public void StopAtInfoPoint(InfoPointController infoPoint)
    {
        if (_navigationMode != NavigationMode.InfoPoint)
            return;

        if (infoPoint != _currentTargetInfoPoint)
            return;

        StopNavigationInternal();

        Debug.Log("Stopped at target info point.");
    }

    public void StopNavigation()
    {
        StopNavigationInternal();
    }

    private void CheckFreeMoveArrival()
    {
        if (agent == null || agent.pathPending)
            return;

        if (agent.remainingDistance <= Mathf.Max(agent.stoppingDistance, freeMoveArrivalDistance))
        {
            if (!agent.hasPath || agent.velocity.sqrMagnitude < 0.01f)
            {
                StopNavigationInternal();
                Debug.Log("Arrived at free-move destination.");
            }
        }
    }

    private void CancelNavigationIfManualInputDetected()
    {
        if (_navigationMode == NavigationMode.None)
            return;

        Vector2 moveInput = _playerActions.Player.Move.ReadValue<Vector2>();

        if (moveInput.sqrMagnitude > 0.01f)
        {
            StopNavigationInternal();
            Debug.Log("Navigation cancelled by manual input.");
        }
    }

    private void StopNavigationInternal()
    {
        if (agent != null)
        {
            agent.isStopped = true;
            agent.ResetPath();
        }

        _navigationMode = NavigationMode.None;
        _currentTargetInfoPoint = null;

        SetManualMovementEnabled(true);
    }

    private void SetManualMovementEnabled(bool enabled)
    {
        if (keyboardController != null)
        {
            keyboardController.SetManualMovementEnabled(enabled);
        }
    }

    public bool IsNavigationActive()
    {
        return _navigationMode != NavigationMode.None;
    }

    public bool IsNavigatingToInfoPoint(InfoPointController infoPoint)
    {
        return _navigationMode == NavigationMode.InfoPoint &&
               _currentTargetInfoPoint == infoPoint;
    }
}