using UnityEngine;
using UnityEngine.AI;
using UnityEngine.InputSystem;

public class PlayerNavigationController : MonoBehaviour
{
    private enum NavigationMode
    {
        None,
        FreeMove,
        InfoPoint
    }

    [Header("References")]
    [SerializeField] private NavMeshAgent _agent;
    [SerializeField] private KeyboardAndMouseController _keyboardController;

    [Header("Arrival Settings")]
    [SerializeField] private float _freeMoveArrivalDistance = 0.2f;

    private NavigationMode _navigationMode = NavigationMode.None;
    private InfoPointController _currentTargetInfoPoint;
    private PlayerActionsAutoGenerated _playerActions;
    private Transform _transform;

    private void Awake()
    {
        if (_agent == null)
            _agent = GetComponent<NavMeshAgent>();

        _playerActions = new PlayerActionsAutoGenerated();
        //agent.updateRotation = false;
        _transform=transform;

}

private void OnEnable()
    {
        _playerActions.Player.Enable();
    }

    private void OnDisable()
    {
        _playerActions.Player.Disable();
    }

    private void Update()
    {
        //CancelNavigationIfManualInputDetected();

        switch (_navigationMode)
        {
            case NavigationMode.FreeMove:
                CheckFreeMoveArrival();
                break;

            case NavigationMode.InfoPoint:
                break;
        }
    }

    public void MoveToPoint(Vector3 destination)
    {
        if (_agent == null)
            return;

        _navigationMode = NavigationMode.FreeMove;
        _currentTargetInfoPoint = null;

        _agent.isStopped = false;
        _agent.updatePosition = true;
        //agent.Warp(transform.position);
        _agent.nextPosition = _transform.position;
        _agent.SetDestination(destination);

        if (_keyboardController != null)
        {
            _keyboardController.BeginLevelView();
            _keyboardController.SetManualMovementEnabled(false);
        }
    }

    public void MoveToInfoPoint(Vector3 destination, InfoPointController infoPoint)
    {
        if (_agent == null || infoPoint == null)
            return;

        _navigationMode = NavigationMode.InfoPoint;
        _currentTargetInfoPoint = infoPoint;

        if (_keyboardController != null)
        {
            _keyboardController.BeginLevelView();
            _keyboardController.SetManualMovementEnabled(false);
        }

        _agent.isStopped = false;
        _agent.updatePosition = true;
        //agent.Warp(transform.position);
        _agent.nextPosition = _transform.position;
        _agent.SetDestination(destination);
    }

    public void StopAtInfoPoint(InfoPointController infoPoint)
    {
        if (_navigationMode != NavigationMode.InfoPoint)
            return;

        if (infoPoint != _currentTargetInfoPoint)
            return;

        StopNavigationInternal();
    }

    public void StopNavigation()
    {
        StopNavigationInternal();
    }

    public void RestoreAgentAfterInfoPoint()
    {
        if (_agent == null)
            return;

        if (!_agent.enabled)
            _agent.enabled = true;

        bool warped = _agent.Warp(transform.position);
        if (!warped)
        {
            Debug.LogWarning("Failed to warp NavMeshAgent back to player position.");
        }

        _agent.isStopped = true;
        _agent.ResetPath();
        _agent.updatePosition = true;
    }

    private void CheckFreeMoveArrival()
    {
        if (_agent == null || _agent.pathPending)
            return;

        if (_agent.remainingDistance <= Mathf.Max(_agent.stoppingDistance, _freeMoveArrivalDistance))
        {
            if (!_agent.hasPath || _agent.velocity.sqrMagnitude < 0.01f)
            {
                StopNavigationInternal();
            }
        }
    }

    private void CancelNavigation()
    {
        if (_navigationMode == NavigationMode.None)
            return;

        Vector2 moveInput = _playerActions.Player.Move.ReadValue<Vector2>();

        if (moveInput.sqrMagnitude > 0.01f)
        {
            StopNavigationInternal();
        }
    }

    private void StopNavigationInternal()
    {
        if (_agent != null)
        {
            _agent.isStopped = true;
            _agent.ResetPath();
            _agent.updatePosition = false;
        }

        _navigationMode = NavigationMode.None;
        _currentTargetInfoPoint = null;
        if (_keyboardController != null)
        {
            _keyboardController.EndLevelView();
            _keyboardController.SetManualMovementEnabled(true);
        }
    }


    public bool IsNavigationActive()
    {
        return _navigationMode != NavigationMode.None;
    }

    public bool IsNavigatingToInfoPoint(InfoPointController infoPoint)
    {
        return _navigationMode == NavigationMode.InfoPoint &&
               _currentTargetInfoPoint == infoPoint;
    }
}