using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.InputSystem;

public class PlayerControlFPS : MonoBehaviour
{
    private PlayerActionsAutoGenerated _playerActions;
    [SerializeField]
    private CharacterController controller;
    [SerializeField]
    private float playerSpeed = 2.0f;

    public bool onScreenJoystick = true;


    
    
    private void Awake()
    {
        //instantiate our actions class so we can access the input system
        _playerActions = new PlayerActionsAutoGenerated();

        _playerActions.Player.Interact.performed += OnInteract;
        
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    void OnInteract(InputAction.CallbackContext context)
    {
        Debug.Log("Interact!");
    }

    // Update is called once per frame
    void Update()
    {
         Vector2 moveVector = _playerActions.Player.Move.ReadValue<Vector2>();
         Vector3 moveController = new Vector3(moveVector.x, 0, moveVector.y);    
        
        
        controller.Move((moveController * (Time.deltaTime * playerSpeed)));
       
        
    }
    
    void OnEnable()
    {
        _playerActions.Player.Enable();
    }
    void OnDisable()
    {
        _playerActions.Player.Disable();
    }
    
    
}
